name: Sync Posts to Firestore

on:
  workflow_dispatch:
  push:
    paths:
      - "src/posts/**/*.md"

jobs:
  sync-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Sync posts to Firestore
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node syncPosts.js
